const ERROR_TYPES = Object.freeze({
  // Genéricos
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Producto
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_CODE_DUPLICATED: 'PRODUCT_CODE_DUPLICATED',

  // Usuario
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_DUPLICATED: 'USER_EMAIL_DUPLICATED',
  INVALID_ROLE: 'INVALID_ROLE',

  // Pedido / Entrega (dominio del Módulo 2)
  PEDIDO_NOT_FOUND: 'PEDIDO_NOT_FOUND',
  ENTREGA_NOT_FOUND: 'ENTREGA_NOT_FOUND',
  INVALID_PEDIDO_STATUS: 'INVALID_PEDIDO_STATUS',

  // Mocks
  INVALID_MOCK_QTY: 'INVALID_MOCK_QTY',
  MOCK_SEED_FAILED: 'MOCK_SEED_FAILED',
});

export default ERROR_TYPES;